- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - golang
    - build-essential

- name: create dspa5 install directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0755
  with_items:
    - /usr/local/src/gocode/src/github.com/naggie/dspa5
    - /usr/local/src/EnglishHTSVoices
    - /var/cache/dspa

- name: copy over dspa5 src
  git:
    repo: "git@github.com:naggie/dspa5.git"
    dest: /usr/local/src/gocode/src/github.com/naggie/dspa5
  notify:
    - build dspa-server
    - restart dspa-server

- name: copy config
  become: yes
  copy:
    src: dspa-server.conf
    dest: /etc/
    mode: 0755
  notify:
    - restart dspa-server

- name: Unarchive voice + engine
  unarchive:
    src: EnglishHTSVoices/EnglishHTSVoices-ver1.0.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/EnglishHTSVoices/do_build

- name: Build voice engine (flite) for PA
  command: sh ./do_build
  args:
    chdir: /usr/local/src/EnglishHTSVoices
    creates: /usr/local/src/EnglishHTSVoices/build/bin/flite_hts_engine

- name: copy speak.sh
  become: yes
  copy:
    src: speak.sh
    dest: /usr/local/src/EnglishHTSVoices/
    mode: 0755

- name: Copy dspa-server systemd service file
  become: yes
  template:
    src: dspa-server.service
    dest: /lib/systemd/system/
    mode: 0644
  notify:
    - reload systemd config

- name: enable dspa-server at boot
  become: yes
  systemd:
    name: dspa-server
    enabled: yes
    masked: no
