- name: create dspa5/install directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0755
  with_items:
    - /usr/local/src/EnglishHTSVoices
    - /var/cache/dspa

- name: download binaries
  get_url:
    url: "{{item.value}}"
    dest: "/usr/local/bin/{{item.key}}"
    mode: 0755
    force: yes
  with_dict:
    "dspa-speaker": "https://github.com/naggie/dspa5/releases/download/{{dspa_version}}/dspa-speaker-linux-amd64"
    "dspa-broadcaster": "https://github.com/naggie/dspa5/releases/download/{{dspa_version}}/dspa-broadcaster-linux-amd64"
    "dspa-client": "https://github.com/naggie/dspa5/releases/download/{{dspa_version}}/dspa-client-linux-amd64"
  become: true

- name: copy config
  become: yes
  template:
    src: dspa-speaker.conf
    dest: /etc/
    mode: 0755

- name: Unarchive voice + engine
  unarchive:
    src: EnglishHTSVoices/EnglishHTSVoices-ver1.0.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/EnglishHTSVoices/do_build

- name: Build voice engine (flite) for PA
  command: sh ./do_build
  args:
    chdir: /usr/local/src/EnglishHTSVoices
    creates: /usr/local/src/EnglishHTSVoices/build/bin/flite_hts_engine

- name: copy speak.sh
  become: yes
  copy:
    src: speak.sh
    dest: /usr/local/src/EnglishHTSVoices/
    mode: 0755

- name: Copy systemd service files
  become: yes
  template:
    src: "{{item}}.service"
    dest: /lib/systemd/system/
    mode: 0644
  with_items:
    - dspa-speaker
    - dspa-broadcaster

# technically should be handler but consequence is low
- name: enable + restart services
  become: yes
  systemd:
    name: "{{item}}"
    enabled: yes
    masked: no
    state: restarted
    daemon_reload: yes
  with_items:
    - dspa-speaker
    - dspa-broadcaster
